# Generated by Django 5.2.8 on 2025-11-29 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('oppo', 'Oppo'), ('vivo', 'Vivo'), ('realme', 'Realme'), ('huawei', 'Huawei'), ('honor', 'Honor'), ('infinix', 'Infinix'), ('tecno', 'Tecno'), ('oneplus', 'OnePlus'), ('google', 'Google Pixel'), ('motorola', 'Motorola'), ('nokia', 'Nokia'), ('sony', 'Sony'), ('asus', 'ASUS'), ('lenovo', 'Lenovo'), ('zte', 'ZTE'), ('meizu', 'Meizu'), ('sharp', 'Sharp'), ('htc', 'HTC'), ('lg', 'LG'), ('blackberry', 'BlackBerry'), ('nothing', 'Nothing'), ('redmagic', 'RedMagic (ZTE Nubia)'), ('rog', 'ASUS ROG Phone'), ('poco', 'POCO'), ('iqoo', 'iQOO')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('flagship', 'Flagship'), ('midrange', 'Midrange'), ('budget', 'Budget')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_main', models.CharField(max_length=255)),
                ('camera_front', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=50)),
                ('screen_size', models.CharField(max_length=50)),
                ('screen_type', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('sim', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='productsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productsapp.product')),
            ],
        ),
    ]
